### ISSUE TITLE
Rule step: Intersection of two sets

### ISSUE THREAD

**Issue by rossjones** [openhealthcare/cedar#13]
_From @davidmiller on October 30, 2014 11:10_

```spec
When "allergy.name" intersects "drug.name"
```

(From openhealthcare/elcid#223 )

_Copied from original issue: openhealthcare/ddd#23_

**Comment by rossjones** [comment]
~~What does ```intersects``` mean in this case?~~

Different question - what are the two sets?

**Comment by rossjones** [comment]
_From @davidmiller on October 30, 2014 11:18_

```
Allergies = [{name: "latex"}, {name: "paracetamol"}]
Drugs = [{name: "morphene"}, {name:"paracetamol"}]
GoodDrugs = [{name: "morphene"}]
```

Allergies.name intersects Drugs.name, it does not intersect GoodDrugs.name

The use case is "If a patient is prescribed something they are allergic to then send back a warning message"

**Comment by michaeledwardmarks** [comment]
Intersections of drugs in particular can be more complicated
For example
Allergy = Co-Amoxiclav
Should trigger an alert if drug ==Any penicillin
Might trigger an alert if drug==any cephlasporin or any carbapenem

**Comment by rossjones** [comment]
Original basic intersection done (:ok when cardinality of intersection > 0).  Will add more complex case as new ticket.
