### ISSUE TITLE
As a developer I would like a better error when I forget to create the database

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/cedar#26]
Currently if you run `mix compile` `mix phoenix.server` we just hang with no failure message.

This gives me sad faces.

OTOH - it's right there in the README so you know, maybe we shouldn't sweat it ? :)

**Comment by rossjones** [comment]
It's the call to Db.wait, it needs to timeout.

**Comment by rossjones** [comment]
Db.wait now has a timeout, and panics it the timeout actually happens. With appropriate panicy response.

**Comment by davidmiller** [comment]
Awesome sauces :D

On 9 February 2015 at 10:57, Ross Jones <notifications@github.com> wrote:

> Closed #26 <https://github.com/openhealthcare/cedar/issues/26>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/cedar/issues/26#event-232377924>.
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883
